import { createApp } from 'vue';
import primeVue from 'primevue/config';
import button from 'primevue/button';
import toastService from 'primevue/toastservice';
import toast from 'primevue/toast';
import card from 'primevue/card';
import dialog from 'primevue/dialog';
import inputText from 'primevue/inputtext';
import textarea from 'primevue/textarea';
import confirmationService from 'primevue/confirmationservice';
import confirmDialog from 'primevue/confirmdialog';
import paginator from 'primevue/paginator';
import App from './App.vue';
import router from './router';

export const app = createApp(App);
app.use(router);
app.use(primeVue);
app.use(toastService);
app.use(confirmationService);
app.component('p-button', button);
app.component('p-toast', toast);
app.component('p-card', card);
app.component('p-dialog', dialog);
app.component('p-inputtext', inputText);
app.component('p-textarea', textarea);
app.component('p-confirm-dialog', confirmDialog);
app.component('p-paginator', paginator);
app.mount('#app');
